[client.pv.activation]
radio = "Radio"

[server.pv.addon.groups.command.create.arg]
name = "<Name>"
password = "<Password>"
permissions = "<List of comma separated permissions>"

[server.pv.addon.groups.arg]
groups_uuid = "<Group Uuid>"
password = "<Password>"

[server.pv.addon.groups]
divider = "&8&m-----------------------------------------------------"

[server.pv.addon.groups.icons]
password_protected = "&9⛨"

[server.pv.addon.groups.tooltip]
password_protected = "Group is password protected"
group_uuid = "Uuid: %s"

[server.pv.addon.groups.format]
group_name = "&9[%s]"
players_and_owner = "&7Players: &r%1$s&7, owned by &r%2$s"
only_players = "&7Players: &r%s"

[server.pv.addon.groups.notifications]
new_owner = "%s is the new owner of the group"
player_joined = "%s joined the group"
player_left = "%s left the group"
group_deleted = "Group was deleted"

[server.pv.addon.groups.button]
join = "&e→ Join"
leave = "&c← Leave"

[server.pv.addon.groups.error]
no_permission = "&cNo permission: %s"
uuid_parse = "'%s' is not a Uuid"