name: Publish

on:
  push:
    branches:
      - release

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Publish to Modrinth/CurseForge
      uses: Apehum/mc-publish@v1.1
      with:
        name: 'PV Addon Priority'

        # modrinth-unfeature-mode: 'none'
        # modrinth-id: 1bZhdhsH
        # modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

        # curseforge-id: 394468
        # curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
        
    - name: Publish to GitHub
      uses: Apehum/mc-publish@v1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        github-generate-changelog: false
